//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor
    {
        //constructor that when called creates hashSets for both Patients and Visits
        public Doctor()
        {
            this.Patients = new HashSet<Patient>();
            this.Visits = new HashSet<Visit>();
        }
        //getters and setters for fields Id, Name, Office, Email, Telephone, Address, Patients and Visits
        public int Id { get; set; }

        [Required(ErrorMessage = "Name Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Office Required")]
        public string Office { get; set; }

        [Required(ErrorMessage = "Email Required")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Telephone Required")]
        public string Telephone { get; set; }
        
        [Required(ErrorMessage = "Address Required")]
        public string Address { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
