//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public Patient()
        {
            this.Visits = new HashSet<Visit>();
        }
        //getters and setters for fields Id, Name, Email, Address, Telephone, Admitted, Discharged, Date Of Birth, Doctor and Visits
        public int Id { get; set; }

        [Required(ErrorMessage = "Name Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email Required")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Address Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Telephone Required")]
        public string Telephone { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Admitted { get; set ; }
        public Nullable<System.DateTime> Discharged { get; set; }

        
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
